name: Chat response suggestions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab==3.4.5
  - pandas==1.4.4
  - regex==2022.8.17
  - scikit-learn==1.1.2
  - scipy==1.9.1
  - seaborn==0.11.2
  - matplotlib==3.5.2
  - make=4.3
  - openpyxl==3.0.9
  - python-dotenv==0.21.0
  - pyodbc==4.0.34
  - pip==22.2.2
  - requests==2.27.1
  - pip:
    - -e .  # make the project editable package, conda >= 4.4 only
    - --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org # to avoid problems with proxies
    # - mariadb is not compatible with the server(os problem)
    - tensorflow  # an OSError can be caused by wrong registry settings: try running regedit and changing
                 #HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem value to 1
    - transformers[torch]==4.20.1 # this fixed version is needed because of inconsistencies in HF pipeline function output ([] vs [[]] problem)
    - rasa==3.2.8
    - spacy==3.4.1
    - next-word-prediction==0.2.0
    - uvicorn== 0.20.0
    - sentence-transformers==2.2.2
  - nltk=3.7
  - fastapi==0.85.0
  - streamlit==1.11.1

