<script>
	import { onMount } from "svelte";
	import ChatMessage from "./ChatMessage.svelte";
	import TodayDivider from "./TodayDivider.svelte";
	import Fa from "svelte-fa";
	// import Api from "./Api.svelte";
	import {
		faUsers,
		faCompressArrowsAlt,
		faComments,
		faEnvelope,
	} from "@fortawesome/free-solid-svg-icons";
	let chat_id = 1;
	let nameMe = "Customer";
	let profilePicMe =
		"https://p0.pikist.com/photos/474/706/boy-portrait-outdoors-facial-men-s-young-t-shirt-hair-person-thumbnail.jpg";

	let nameChatPartner = "Agent";
	let profilePicChatPartner =
		"https://storage.needpix.com/rsynced_images/male-teacher-cartoon.jpg";
	let searchTerm = "";
	let last_customer_msg_id = 0;
	let promise;
	let src = "";
	$: if (searchTerm != "") {
		promise = getPhoto();
	}

	async function getPhoto() {
		let thisSearchTerm = searchTerm;
		const url = "http://127.0.0.1:8031/get_data";
		const res = await fetch(url);
		let photoUrl = res.json();
		if (res.ok && thisSearchTerm == searchTerm) {
			src = photoUrl;
		}
	}
</script>

<input type="text" placeholder="dog, car, house" bind:value={searchTerm} />
<img
	{src}
	alt="An image generated by searching for {searchTerm}."
	class:invisible={!src}
/>
<svelte:head>
	<link
		rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	/>
</svelte:head>
<div class="card card-danger direct-chat direct-chat-danger">
	<div class="card-header">
		<div class="card-tools d-flex">
			<img
				class="contacts-img"
				src={profilePicChatPartner}
				alt="profilePic"
			/>
			<span class="contacts-name">{nameChatPartner}</span>
			<span class="mr-auto" />
			<button type="button" class="btn btn-tool" title="Contacts"
				><Fa icon={faUsers} /></button
			>
			<button type="button" class="btn btn-tool"
				><Fa icon={faCompressArrowsAlt} /></button
			>
		</div>
	</div>
	<div class="card-body">
		<div class="direct-chat-messages">
			{#each { src } as message}
				<ChatMessage
					{nameMe}
					{profilePicMe}
					{nameChatPartner}
					{profilePicChatPartner}
					message={message.message}
					timestamp={message.timestamp}
					sentByMe={message.sentByMe}
					timeRead={message.timeRead}
				/>
			{/each}
		</div>
	</div>
	<div class="card-footer">
		<div class="input-group">
			<input
				type="text"
				placeholder="Type Message ..."
				class="form-control"
			/>
			<span class="input-group-append">
				<button type="button" class="btn btn-primary">Send</button>
			</span>
		</div>
	</div>
</div>

{#await promise}
	<div class="loading"><img src="/loading.gif" alt="Loading..." /></div>
{/await}

<style>
	.direct-chat .card-body {
		overflow-x: hidden;
		padding: 0;
		position: relative;
	}

	.direct-chat-messages {
		-webkit-transform: translate(0, 0);
		transform: translate(0, 0);
		height: 400px;
		overflow: auto;
		padding: 10px;
		transition: -webkit-transform 0.5s ease-in-out;
		transition: transform 0.5s ease-in-out;
		transition: transform 0.5s ease-in-out,
			-webkit-transform 0.5s ease-in-out;
	}

	.contacts-img {
		border-radius: 50%;
		width: 40px;
		height: 40px;
	}
	.contacts-name {
		margin-left: 15px;
		font-weight: 600;
	}
</style>
